module.exports = {
  "ant-prefix": "ksyun",
  "primary-color": "#0091ea",
  "success-color": "#36b342",
  "info-color": "@primary-color",
  "warning-color": "#ff9800",
  "error-color": "#ff4133",
  "processing-color": "@primary-color",
  "heading-color": "#333333",
  "text-color": "#4c4c4c",
  "text-color-secondary": "fade(#000, 45%)",
  "border-color-base": "#cccccc",
  "border-color-split": "#dedede",
  "layout-header-background": "#262626",
  "layout-body-background": "#fafafa",
  "font-size-base": "12px",
  "border-radius-sm": "0",
  "disabled-color": "#cccccc",
  "disabled-bg": "#f2f2f2",
  "outline-width": "0",
  "outline-color": "#737373",
  "background-color-base": "#f1f1f5",
  "shadow-color": "#000000",
  "btn-default-bg": "#fafafa",
  "btn-default-border": "#dedede",
  "radio-button-bg": "transparent",
  "radio-button-checked-bg": "transparent",
  "form-item-margin-bottom": "16px",
  "input-height-lg": "36px",
  "input-placeholder-color": "#b2b2b2",
  "input-hover-border-color": "#737373",
  "progress-radius": "0",
  "table-header-bg": "#fafafa",
  "table-row-hover-bg": "#fafafa",
  "table-padding-vertical": "15px",
  "tabs-card-gutter": "-1px",
  "tabs-card-tab-active-border-top": "2px solid primary-color",
  "switch-height": "18px",
  "switch-color": "@success-color",
  "switch-shadow-color": "fade(#00230b, 20%)",
  "breadcrumb-base-color": "@text-color",
  "breadcrumb-last-item-color": "@text-color-secondary",
  "slider-handle-border-width": "1px",
  "slider-handle-shadow": "1px 1px 4px 0 rgba(0,0,0,.13)",
  "slider-track-background-color": "@primary-color",
  "slider-track-background-color-hover": "@primary-color",
  "slider-handle-color": "#dedede",
  "slider-handle-color-hover": "#dedede",
  "slider-handle-color-focus": "#dedede",
  "slider-handle-color-focus-shadow": "transparent",
  "slider-handle-color-tooltip-open": "#ddd",
  "alert-success-border-color": "#dff4e5",
  "alert-success-bg-color": "#dff4e5",
  "alert-info-border-color": "#e5f3ff",
  "alert-info-bg-color": "#e5f3ff",
  "alert-warning-border-color": "#fff7db",
  "alert-warning-bg-color": "#fff7db",
  "alert-error-border-color": "#fcebea",
  "alert-error-bg-color": "#fcebea",
};
